import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { catchError, map } from 'rxjs';
import { IUser } from 'src/app/shared/models/user-interface/iuser';
import { StorageService } from 'src/app/shared/services/storage-service/storage.service';
import { UserService } from 'src/app/shared/services/user-service/user.service';
import { emailAsyncValidator, passwordCMatchValidator, strValidator, whitespaceStr } from 'src/app/shared/validators/form-validators';

@Component({
  selector: 'app-registration',
  templateUrl: './registration.component.html',
  styleUrls: ['./registration.component.css']
})
export class RegistrationComponent  implements OnInit {

  //variables declaration
  _registrationForm!: FormGroup;
  _userDetails!: IUser;
  _registeredUser!: IUser; 
  _errorMessage: string = '';
  _registrationStatus: boolean = false;

  constructor(
    private _router: Router,
    private _authStorage: StorageService,
    private _userServie: UserService) {  
  }

  ngOnInit(): void { 
    
     //Clear the current logggedIn user session if any
    if (this._authStorage.getUser() != null) {
      sessionStorage.clear();
    }

    //Initialize the form
    this._registrationForm = new FormGroup({
        firstName: new FormControl('', [Validators.required, strValidator(), whitespaceStr()]),
        emailAddress: new FormControl('', [Validators.required, Validators.email], [ emailAsyncValidator(this._userServie)]),
        password: new FormControl('', [Validators.required, Validators.minLength(8)]),
        rePassword: new FormControl('', [Validators.required])
    },
      {
        //custom validation - password mismatch
        validators: passwordCMatchValidator('password', 'rePassword')
    });
    
  }

  //getter for form-control[firstName]
  get firstName() {
    return this._registrationForm.get('firstName');}

  //getter for form-control[emailAddress]
  get emailAddress() {
    return this._registrationForm.get('emailAddress');}
  
  //getter for form-control [password]
  get password() {
    return this._registrationForm.get('password');}
  
  //getter for form-control [rePassword]
  get rePassword() {
    return this._registrationForm.get('rePassword');
  }
  
  register() {

    let formData: any;
     //Prevent posting empty invalid or empty registration form  
    if (this._registrationForm.invalid) {
      this._errorMessage = "* Please enter all the required user details"
      return;
    } else {
      formData = this._registrationForm.value;
    }
  
    //Map form values as per required http post parameter(IUser)
    this._userDetails = this.setUserDetails(formData);

    this._userServie.registerUser(this._userDetails).pipe(map((_httpResponse: any) => {
      
      if (!_httpResponse) {
        throw "Something went wrong in the server";
      } else if (Object.keys(_httpResponse).length === 0) {

        console.log(" -- http response - [unscuccessful] --");
        console.log(_httpResponse);
        throw "Registration unssuccessfull!";
      } else {

        this._registeredUser = _httpResponse;

        console.log(" -- http response - [successful] --");
        console.log(_httpResponse);
        this.resetForm();
      }
      return this._registeredUser;
    }),
      
    catchError(error => {
        throw error;
    })
    ).subscribe({
      next: (_registeredUser: IUser) => {

        this._authStorage.storeUser(_registeredUser);
        this._router.navigate(['/dashboard']);
        
      },
      error: (_error: Error) => {
        if (Error) {
          this._errorMessage = Error.name.toString();
        }
      }
    });  
    
  }

  //Map http post parameters[IUser]
  setUserDetails(formData: any) {

    let userDetails: any;
      userDetails = {
     //id - will be autoGenerated on the server side
      name: formData.firstName,
      emailAddress: formData.emailAddress,
      password: formData.password,
      };
    
    return userDetails;

  }

  //Clear the regitration form
  resetForm() {
    this._registrationForm.reset();
    this._errorMessage = '';
  }  
}
